In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
import statsmodels.formula.api as smf
from scipy.special import expit
from scipy.stats import logistic

%matplotlib inline

In [14]:
pd.set_option('display.max_columns', None)

In [2]:
df1 = pd.read_csv("2015_-_2016_Students_with_Multiple_Removals_or_Suspensions.csv")
df2 = pd.read_csv("2015-16_Multiple_Removals_-_Race.csv")
df3 = pd.read_csv("2015-16_Multiple_Removals_-_SWD.csv")
df4 = pd.read_csv("2015-16_Multiple_Removals_-_Year_of_Birth.csv")
df5 = pd.read_csv("2015-16_Multiple_Removals_-_Grade_Level.csv")
df6 = pd.read_csv("2015-16_Multiple_Removals_-_Gender.csv")

In [15]:
df1.head()

,DBN,LOCATION NAME,LOCATION CATEGORY,ADMINISTRATIVE DISTRICT,AMERICAN INDIAN/ALASKAN NATIVE STUDENTS With 2 or More Suspensions or Removals,ASIAN STUDENTS With 2 or More Suspensions or Removals,BLACK STUDENTS With 2 or More Suspensions or Removals,HISPANIC STUDENTS With 2 or More Suspensions or Removals,WHITE STUDENTS With 2 or More Suspensions or Removals,MULTI-RACIAL STUDENTS With 2 or More Suspensions or Removals,UNKNOWN STUDENTS With 2 or More Suspensions or Removals,TOTAL STUDENTS With 2 or More Suspensions or Removals
0,01M015,P.S. 015 Roberto Clemente,Elementary,1.0,*,*,*,*,*,*,*,*
1,01M019,P.S. 019 Asher Levy,Elementary,1.0,*,*,*,*,*,*,*,*
2,01M020,P.S. 020 Anna Silver,Elementary,1.0,*,*,*,*,*,*,*,*
3,01M034,P.S. 034 Franklin D. Roosevelt,K-8,1.0,*,*,*,*,*,*,*,14
4,01M063,The STAR Academy - P.S.63,Elementary,1.0,*,*,*,*,*,*,*,6

In [16]:
df2.head()

,DBN,LOCATION NAME,LOCATION CATEGORY,ADMINISTRATIVE DISTRICT,AMERICAN INDIAN/ALASKAN NATIVE STUDENTS With 2 or More Suspensions or Removals,ASIAN STUDENTS With 2 or More Suspensions or Removals,BLACK STUDENTS With 2 or More Suspensions or Removals,HISPANIC STUDENTS With 2 or More Suspensions or Removals,WHITE STUDENTS With 2 or More Suspensions or Removals,MULTI-RACIAL STUDENTS With 2 or More Suspensions or Removals,UNKNOWN STUDENTS With 2 or More Suspensions or Removals,TOTAL STUDENTS With 2 or More Suspensions or Removals
0,01M015,P.S. 015 Roberto Clemente,Elementary,1.0,*,*,*,*,*,*,*,*
1,01M019,P.S. 019 Asher Levy,Elementary,1.0,*,*,*,*,*,*,*,*
2,01M020,P.S. 020 Anna Silver,Elementary,1.0,*,*,*,*,*,*,*,*
3,01M034,P.S. 034 Franklin D. Roosevelt,K-8,1.0,*,*,*,*,*,*,*,14
4,01M063,The STAR Academy - P.S.63,Elementary,1.0,*,*,*,*,*,*,*,6

In [17]:
df6.head()

,DBN,LOCATION NAME,LOCATION CATEGORY,ADMINISTRATIVE DISTRICT,FEMALE STUDENTS With 2 or More Suspensions or Removals,MALE STUDENTS With 2 or More Suspensions or Removals,TOTAL STUDENTS With 2 or More Suspensions or Removals
0,01M015,P.S. 015 Roberto Clemente,Elementary,1.0,*,*,*
1,01M019,P.S. 019 Asher Levy,Elementary,1.0,*,*,*
2,01M020,P.S. 020 Anna Silver,Elementary,1.0,*,*,*
3,01M034,P.S. 034 Franklin D. Roosevelt,K-8,1.0,8,6,14
4,01M063,The STAR Academy - P.S.63,Elementary,1.0,*,*,6

In [18]:
df3.head()

,DBN,LOCATION NAME,LOCATION CATEGORY,ADMINISTRATIVE DISTRICT,GEN ED STUDENTS With 2 or More Suspensions or Removals,SWD STUDENTS With 2 or More Suspensions or Removals,TOTAL STUDENTS With 2 or More Suspensions or Removals
0,01M015,P.S. 015 Roberto Clemente,Elementary,1.0,*,*,*
1,01M019,P.S. 019 Asher Levy,Elementary,1.0,*,*,*
2,01M020,P.S. 020 Anna Silver,Elementary,1.0,*,*,*
3,01M034,P.S. 034 Franklin D. Roosevelt,K-8,1.0,8,6,14
4,01M063,The STAR Academy - P.S.63,Elementary,1.0,*,*,6

In [19]:
df4.head()

,DBN,LOCATION NAME,LOCATION CATEGORY,ADMINISTRATIVE DISTRICT,5 STUDENTS With 2 or More Suspensions or Removals,6 STUDENTS With 2 or More Suspensions or Removals,7 STUDENTS With 2 or More Suspensions or Removals,8 STUDENTS With 2 or More Suspensions or Removals,9 STUDENTS With 2 or More Suspensions or Removals,10 STUDENTS With 2 or More Suspensions or Removals,11 STUDENTS With 2 or More Suspensions or Removals,12 STUDENTS With 2 or More Suspensions or Removals,13 STUDENTS With 2 or More Suspensions or Removals,14 STUDENTS With 2 or More Suspensions or Removals,15 STUDENTS With 2 or More Suspensions or Removals,16 STUDENTS With 2 or More Suspensions or Removals,17 STUDENTS With 2 or More Suspensions or Removals,18 STUDENTS With 2 or More Suspensions or Removals,19 STUDENTS With 2 or More Suspensions or Removals,20 STUDENTS With 2 or More Suspensions or Removals,21 STUDENTS With 2 or More Suspensions or Removals,TOTAL STUDENTS With 2 or More Suspensions or Removals
0,01M015,P.S. 015 Roberto Clemente,Elementary,1.0,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*
1,01M019,P.S. 019 Asher Levy,Elementary,1.0,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*
2,01M020,P.S. 020 Anna Silver,Elementary,1.0,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*
3,01M034,P.S. 034 Franklin D. Roosevelt,K-8,1.0,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,14
4,01M063,The STAR Academy - P.S.63,Elementary,1.0,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,6

In [20]:
df5.head()

,DBN,LOCATION NAME,LOCATION CATEGORY,ADMINISTRATIVE DISTRICT,0K STUDENTS With 2 or More Suspensions or Removals,01 STUDENTS With 2 or More Suspensions or Removals,02 STUDENTS With 2 or More Suspensions or Removals,03 STUDENTS With 2 or More Suspensions or Removals,04 STUDENTS With 2 or More Suspensions or Removals,05 STUDENTS With 2 or More Suspensions or Removals,06 STUDENTS With 2 or More Suspensions or Removals,07 STUDENTS With 2 or More Suspensions or Removals,08 STUDENTS With 2 or More Suspensions or Removals,09 STUDENTS With 2 or More Suspensions or Removals,10 STUDENTS With 2 or More Suspensions or Removals,11 STUDENTS With 2 or More Suspensions or Removals,12 STUDENTS With 2 or More Suspensions or Removals,TOTAL STUDENTS With 2 or More Suspensions or Removals
0,01M015,P.S. 015 Roberto Clemente,Elementary,1.0,*,*,*,*,*,*,*,*,*,*,*,*,*,*
1,01M019,P.S. 019 Asher Levy,Elementary,1.0,*,*,*,*,*,*,*,*,*,*,*,*,*,*
2,01M020,P.S. 020 Anna Silver,Elementary,1.0,*,*,*,*,*,*,*,*,*,*,*,*,*,*
3,01M034,P.S. 034 Franklin D. Roosevelt,K-8,1.0,*,*,*,*,*,*,*,*,*,*,*,*,*,14
4,01M063,The STAR Academy - P.S.63,Elementary,1.0,*,*,*,*,*,*,*,*,*,*,*,*,*,6

In [37]:
df1.shape

AttributeError: 'DataFrame' object has no attribute 'shape'

In [ ]:
!pip install --user dask

In [ ]:
!pip install --user toolz

In [ ]:
!pip install --user cloudpickle

In [ ]:
!pip install --user methods

In [ ]:
!pip install --user "dask[complete]"

In [6]:
# kept getting errors until I restarted the kernel
#as per  https://github.com/dask/dask/issues/3348

In [4]:
import dask.dataframe as dd

In [32]:
# Read in the csv files.
#df1 = dd.read_csv('2015_-_2016_Students_with_Multiple_Removals_or_Suspensions.csv')
#df2 = dd.read_csv('2015-16_Multiple_Removals_-_Race.csv')


df1 = dd.read_csv("2015_-_2016_Students_with_Multiple_Removals_or_Suspensions.csv")
df2 = dd.read_csv("2015-16_Multiple_Removals_-_Race.csv")
df3 = dd.read_csv("2015-16_Multiple_Removals_-_SWD.csv")
df4 = dd.read_csv("2015-16_Multiple_Removals_-_Year_of_Birth.csv")
df5 = dd.read_csv("2015-16_Multiple_Removals_-_Grade_Level.csv")
df6 = dd.read_csv("2015-16_Multiple_Removals_-_Gender.csv")

# Merge the csv files.

#df = dd.merge(df1, df2, on='DBN').compute()

dff = dd.merge(dfe, df6, on='DBN').compute()


# Write the output.
dff.to_csv('school_suspensions_merged.csv', index=False)

In [33]:
suspensions = pd.read_csv("school_suspensions_merged.csv")
suspensions.head()

,DBN,LOCATION NAME_x,LOCATION CATEGORY_x,ADMINISTRATIVE DISTRICT_x,AMERICAN INDIAN/ALASKAN NATIVE STUDENTS With 2 or More Suspensions or Removals_x,ASIAN STUDENTS With 2 or More Suspensions or Removals_x,BLACK STUDENTS With 2 or More Suspensions or Removals_x,HISPANIC STUDENTS With 2 or More Suspensions or Removals_x,WHITE STUDENTS With 2 or More Suspensions or Removals_x,MULTI-RACIAL STUDENTS With 2 or More Suspensions or Removals_x,UNKNOWN STUDENTS With 2 or More Suspensions or Removals_x,TOTAL STUDENTS With 2 or More Suspensions or Removals_x,LOCATION NAME_y,LOCATION CATEGORY_y,ADMINISTRATIVE DISTRICT_y,AMERICAN INDIAN/ALASKAN NATIVE STUDENTS With 2 or More Suspensions or Removals_y,ASIAN STUDENTS With 2 or More Suspensions or Removals_y,BLACK STUDENTS With 2 or More Suspensions or Removals_y,HISPANIC STUDENTS With 2 or More Suspensions or Removals_y,WHITE STUDENTS With 2 or More Suspensions or Removals_y,MULTI-RACIAL STUDENTS With 2 or More Suspensions or Removals_y,UNKNOWN STUDENTS With 2 or More Suspensions or Removals_y,TOTAL STUDENTS With 2 or More Suspensions or Removals_y,LOCATION NAME_x.1,LOCATION CATEGORY_x.1,ADMINISTRATIVE DISTRICT_x.1,GEN ED STUDENTS With 2 or More Suspensions or Removals_x,SWD STUDENTS With 2 or More Suspensions or Removals_x,TOTAL STUDENTS With 2 or More Suspensions or Removals_x.1,LOCATION NAME_y.1,LOCATION CATEGORY_y.1,ADMINISTRATIVE DISTRICT_y.1,GEN ED STUDENTS With 2 or More Suspensions or Removals_y,SWD STUDENTS With 2 or More Suspensions or Removals_y,TOTAL STUDENTS With 2 or More Suspensions or Removals_y.1,LOCATION NAME_x.2,LOCATION CATEGORY_x.2,ADMINISTRATIVE DISTRICT_x.2,5 STUDENTS With 2 or More Suspensions or Removals,6 STUDENTS With 2 or More Suspensions or Removals,7 STUDENTS With 2 or More Suspensions or Removals,8 STUDENTS With 2 or More Suspensions or Removals,9 STUDENTS With 2 or More Suspensions or Removals,10 STUDENTS With 2 or More Suspensions or Removals_x,11 STUDENTS With 2 or More Suspensions or Removals_x,12 STUDENTS With 2 or More Suspensions or Removals_x,13 STUDENTS With 2 or More Suspensions or Removals,14 STUDENTS With 2 or More Suspensions or Removals,15 STUDENTS With 2 or More Suspensions or Removals,16 STUDENTS With 2 or More Suspensions or Removals,17 STUDENTS With 2 or More Suspensions or Removals,18 STUDENTS With 2 or More Suspensions or Removals,19 STUDENTS With 2 or More Suspensions or Removals,20 STUDENTS With 2 or More Suspensions or Removals,21 STUDENTS With 2 or More Suspensions or Removals,TOTAL STUDENTS With 2 or More Suspensions or Removals_x.2,LOCATION NAME_y.2,LOCATION CATEGORY_y.2,ADMINISTRATIVE DISTRICT_y.2,0K STUDENTS With 2 or More Suspensions or Removals,01 STUDENTS With 2 or More Suspensions or Removals,02 STUDENTS With 2 or More Suspensions or Removals,03 STUDENTS With 2 or More Suspensions or Removals,04 STUDENTS With 2 or More Suspensions or Removals,05 STUDENTS With 2 or More Suspensions or Removals,06 STUDENTS With 2 or More Suspensions or Removals,07 STUDENTS With 2 or More Suspensions or Removals,08 STUDENTS With 2 or More Suspensions or Removals,09 STUDENTS With 2 or More Suspensions or Removals,10 STUDENTS With 2 or More Suspensions or Removals_y,11 STUDENTS With 2 or More Suspensions or Removals_y,12 STUDENTS With 2 or More Suspensions or Removals_y,TOTAL STUDENTS With 2 or More Suspensions or Removals_y.2,LOCATION NAME,LOCATION CATEGORY,ADMINISTRATIVE DISTRICT,FEMALE STUDENTS With 2 or More Suspensions or Removals,MALE STUDENTS With 2 or More Suspensions or Removals,TOTAL STUDENTS With 2 or More Suspensions or Removals
0,01M015,P.S. 015 Roberto Clemente,Elementary,1.0,*,*,*,*,*,*,*,*,P.S. 015 Roberto Clemente,Elementary,1.0,*,*,*,*,*,*,*,*,P.S. 015 Roberto Clemente,Elementary,1.0,*,*,*,P.S. 015 Roberto Clemente,Elementary,1.0,*,*,*,P.S. 015 Roberto Clemente,Elementary,1.0,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,P.S. 015 Roberto Clemente,Elementary,1.0,*,*,*,*,*,*,*,*,*,*,*,*,*,*,P.S. 015 Roberto Clemente,Elementary,1.0,*,*,*
1,01M019,P.S. 019 Asher Levy,Elementary,1.0,*,*,*,*,*,*,*,*,P.S. 019 Asher Levy,Elementary,1.0,*,*,*,*,*,*,*,*,P.S. 019 Asher Levy,Elementary,1.0,*,*,*,P.S. 019 Asher Levy,Elementary,1.0,*,*,*,P.S. 019 Asher Levy,Elementary,1.0,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,P.S. 019 Asher Levy,Elementary,1.0,*,*,*,*,*,*,*,*,*,*,*,*,*,*,P.S. 019 Asher Levy,Elementary,1.0,*,*,*
2,01M020,P.S. 020 Anna Silver,Elementary,1.0,*,*,*,*,*,*,*,*,P.S. 020 Anna Silver,Elementary,1.0,*,*,*,*,*,*,*,*,P.S. 020 Anna Silver,Elementary,1.0,*,*,*,P.S. 020 Anna Silver,Elementary,1.0,*,*,*,P.S. 020 Anna Silver,Elementary,1.0,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,P.S. 020 Anna Silver,Elementary,1.0,*,*,*,*,*,*,*,*,*,*,*,*,*,*,P.S. 020 Anna Silver,Elementary,1.0,*,*,*
3,01M034,P.S. 034 Franklin D. Roosevelt,K-8,1.0,*,*,*,*,*,*,*,14,P.S. 034 Franklin D. Roosevelt,K-8,1.0,*,*,*,*,*,*,*,14,P.S. 034 Franklin D. Roosevelt,K-8,1.0,8,6,14,P.S. 034 Franklin D. Roosevelt,K-8,1.0,8,6,14,P.S. 034 Franklin D. Roosevelt,K-8,1.0,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,14,P.S. 034 Franklin D. Roosevelt,K-8,1.0,*,*,*,*,*,*,*,*,*,*,*,*,*,14,P.S. 034 Franklin D. Roosevelt,K-8,1.0,8,6,14
4,01M063,The STAR Academy - P.S.63,Elementary,1.0,*,*,*,*,*,*,*,6,The STAR Academy - P.S.63,Elementary,1.0,*,*,*,*,*,*,*,6,The STAR Academy - P.S.63,Elementary,1.0,*,*,6,The STAR Academy - P.S.63,Elementary,1.0,*,*,6,The STAR Academy - P.S.63,Elementary,1.0,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,6,The STAR Academy - P.S.63,Elementary,1.0,*,*,*,*,*,*,*,*,*,*,*,*,*,6,The STAR Academy - P.S.63,Elementary,1.0,*,*,6

In [34]:
suspensions.shape

(1743, 79)

In [38]:
suspensions.head()

,DBN,LOCATION NAME_x,LOCATION CATEGORY_x,ADMINISTRATIVE DISTRICT_x,AMERICAN INDIAN/ALASKAN NATIVE STUDENTS With 2 or More Suspensions or Removals_x,ASIAN STUDENTS With 2 or More Suspensions or Removals_x,BLACK STUDENTS With 2 or More Suspensions or Removals_x,HISPANIC STUDENTS With 2 or More Suspensions or Removals_x,WHITE STUDENTS With 2 or More Suspensions or Removals_x,MULTI-RACIAL STUDENTS With 2 or More Suspensions or Removals_x,UNKNOWN STUDENTS With 2 or More Suspensions or Removals_x,TOTAL STUDENTS With 2 or More Suspensions or Removals_x,LOCATION NAME_y,LOCATION CATEGORY_y,ADMINISTRATIVE DISTRICT_y,AMERICAN INDIAN/ALASKAN NATIVE STUDENTS With 2 or More Suspensions or Removals_y,ASIAN STUDENTS With 2 or More Suspensions or Removals_y,BLACK STUDENTS With 2 or More Suspensions or Removals_y,HISPANIC STUDENTS With 2 or More Suspensions or Removals_y,WHITE STUDENTS With 2 or More Suspensions or Removals_y,MULTI-RACIAL STUDENTS With 2 or More Suspensions or Removals_y,UNKNOWN STUDENTS With 2 or More Suspensions or Removals_y,TOTAL STUDENTS With 2 or More Suspensions or Removals_y,LOCATION NAME_x.1,LOCATION CATEGORY_x.1,ADMINISTRATIVE DISTRICT_x.1,GEN ED STUDENTS With 2 or More Suspensions or Removals_x,SWD STUDENTS With 2 or More Suspensions or Removals_x,TOTAL STUDENTS With 2 or More Suspensions or Removals_x.1,LOCATION NAME_y.1,LOCATION CATEGORY_y.1,ADMINISTRATIVE DISTRICT_y.1,GEN ED STUDENTS With 2 or More Suspensions or Removals_y,SWD STUDENTS With 2 or More Suspensions or Removals_y,TOTAL STUDENTS With 2 or More Suspensions or Removals_y.1,LOCATION NAME_x.2,LOCATION CATEGORY_x.2,ADMINISTRATIVE DISTRICT_x.2,5 STUDENTS With 2 or More Suspensions or Removals,6 STUDENTS With 2 or More Suspensions or Removals,7 STUDENTS With 2 or More Suspensions or Removals,8 STUDENTS With 2 or More Suspensions or Removals,9 STUDENTS With 2 or More Suspensions or Removals,10 STUDENTS With 2 or More Suspensions or Removals_x,11 STUDENTS With 2 or More Suspensions or Removals_x,12 STUDENTS With 2 or More Suspensions or Removals_x,13 STUDENTS With 2 or More Suspensions or Removals,14 STUDENTS With 2 or More Suspensions or Removals,15 STUDENTS With 2 or More Suspensions or Removals,16 STUDENTS With 2 or More Suspensions or Removals,17 STUDENTS With 2 or More Suspensions or Removals,18 STUDENTS With 2 or More Suspensions or Removals,19 STUDENTS With 2 or More Suspensions or Removals,20 STUDENTS With 2 or More Suspensions or Removals,21 STUDENTS With 2 or More Suspensions or Removals,TOTAL STUDENTS With 2 or More Suspensions or Removals_x.2,LOCATION NAME_y.2,LOCATION CATEGORY_y.2,ADMINISTRATIVE DISTRICT_y.2,0K STUDENTS With 2 or More Suspensions or Removals,01 STUDENTS With 2 or More Suspensions or Removals,02 STUDENTS With 2 or More Suspensions or Removals,03 STUDENTS With 2 or More Suspensions or Removals,04 STUDENTS With 2 or More Suspensions or Removals,05 STUDENTS With 2 or More Suspensions or Removals,06 STUDENTS With 2 or More Suspensions or Removals,07 STUDENTS With 2 or More Suspensions or Removals,08 STUDENTS With 2 or More Suspensions or Removals,09 STUDENTS With 2 or More Suspensions or Removals,10 STUDENTS With 2 or More Suspensions or Removals_y,11 STUDENTS With 2 or More Suspensions or Removals_y,12 STUDENTS With 2 or More Suspensions or Removals_y,TOTAL STUDENTS With 2 or More Suspensions or Removals_y.2,LOCATION NAME,LOCATION CATEGORY,ADMINISTRATIVE DISTRICT,FEMALE STUDENTS With 2 or More Suspensions or Removals,MALE STUDENTS With 2 or More Suspensions or Removals,TOTAL STUDENTS With 2 or More Suspensions or Removals
0,01M015,P.S. 015 Roberto Clemente,Elementary,1.0,*,*,*,*,*,*,*,*,P.S. 015 Roberto Clemente,Elementary,1.0,*,*,*,*,*,*,*,*,P.S. 015 Roberto Clemente,Elementary,1.0,*,*,*,P.S. 015 Roberto Clemente,Elementary,1.0,*,*,*,P.S. 015 Roberto Clemente,Elementary,1.0,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,P.S. 015 Roberto Clemente,Elementary,1.0,*,*,*,*,*,*,*,*,*,*,*,*,*,*,P.S. 015 Roberto Clemente,Elementary,1.0,*,*,*
1,01M019,P.S. 019 Asher Levy,Elementary,1.0,*,*,*,*,*,*,*,*,P.S. 019 Asher Levy,Elementary,1.0,*,*,*,*,*,*,*,*,P.S. 019 Asher Levy,Elementary,1.0,*,*,*,P.S. 019 Asher Levy,Elementary,1.0,*,*,*,P.S. 019 Asher Levy,Elementary,1.0,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,P.S. 019 Asher Levy,Elementary,1.0,*,*,*,*,*,*,*,*,*,*,*,*,*,*,P.S. 019 Asher Levy,Elementary,1.0,*,*,*
2,01M020,P.S. 020 Anna Silver,Elementary,1.0,*,*,*,*,*,*,*,*,P.S. 020 Anna Silver,Elementary,1.0,*,*,*,*,*,*,*,*,P.S. 020 Anna Silver,Elementary,1.0,*,*,*,P.S. 020 Anna Silver,Elementary,1.0,*,*,*,P.S. 020 Anna Silver,Elementary,1.0,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,P.S. 020 Anna Silver,Elementary,1.0,*,*,*,*,*,*,*,*,*,*,*,*,*,*,P.S. 020 Anna Silver,Elementary,1.0,*,*,*
3,01M034,P.S. 034 Franklin D. Roosevelt,K-8,1.0,*,*,*,*,*,*,*,14,P.S. 034 Franklin D. Roosevelt,K-8,1.0,*,*,*,*,*,*,*,14,P.S. 034 Franklin D. Roosevelt,K-8,1.0,8,6,14,P.S. 034 Franklin D. Roosevelt,K-8,1.0,8,6,14,P.S. 034 Franklin D. Roosevelt,K-8,1.0,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,14,P.S. 034 Franklin D. Roosevelt,K-8,1.0,*,*,*,*,*,*,*,*,*,*,*,*,*,14,P.S. 034 Franklin D. Roosevelt,K-8,1.0,8,6,14
4,01M063,The STAR Academy - P.S.63,Elementary,1.0,*,*,*,*,*,*,*,6,The STAR Academy - P.S.63,Elementary,1.0,*,*,*,*,*,*,*,6,The STAR Academy - P.S.63,Elementary,1.0,*,*,6,The STAR Academy - P.S.63,Elementary,1.0,*,*,6,The STAR Academy - P.S.63,Elementary,1.0,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,6,The STAR Academy - P.S.63,Elementary,1.0,*,*,*,*,*,*,*,*,*,*,*,*,*,6,The STAR Academy - P.S.63,Elementary,1.0,*,*,6

In [42]:
suspensionData = pd.read_csv("211516suspensions.csv")

In [43]:
suspensionData.head()

,DBN,LOCATION NAME_x,LOCATION CATEGORY_x,ADMINISTRATIVE DISTRICT_x,AMERICAN INDIAN/ALASKAN NATIVE STUDENTS With 2 or More Suspensions or Removals_x,ASIAN STUDENTS With 2 or More Suspensions or Removals_x,BLACK STUDENTS With 2 or More Suspensions or Removals_x,HISPANIC STUDENTS With 2 or More Suspensions or Removals_x,WHITE STUDENTS With 2 or More Suspensions or Removals_x,MULTI-RACIAL STUDENTS With 2 or More Suspensions or Removals_x,UNKNOWN STUDENTS With 2 or More Suspensions or Removals_x,TOTAL STUDENTS With 2 or More Suspensions or Removals_x,AMERICAN INDIAN/ALASKAN NATIVE STUDENTS With 2 or More Suspensions or Removals_y,ASIAN STUDENTS With 2 or More Suspensions or Removals_y,BLACK STUDENTS With 2 or More Suspensions or Removals_y,HISPANIC STUDENTS With 2 or More Suspensions or Removals_y,WHITE STUDENTS With 2 or More Suspensions or Removals_y,MULTI-RACIAL STUDENTS With 2 or More Suspensions or Removals_y,UNKNOWN STUDENTS With 2 or More Suspensions or Removals_y,TOTAL STUDENTS With 2 or More Suspensions or Removals_y,GEN ED STUDENTS With 2 or More Suspensions or Removals_x,SWD STUDENTS With 2 or More Suspensions or Removals_x,TOTAL STUDENTS With 2 or More Suspensions or Removals_x.1,GEN ED STUDENTS With 2 or More Suspensions or Removals_y,SWD STUDENTS With 2 or More Suspensions or Removals_y,TOTAL STUDENTS With 2 or More Suspensions or Removals_y.1,5 STUDENTS With 2 or More Suspensions or Removals,6 STUDENTS With 2 or More Suspensions or Removals,7 STUDENTS With 2 or More Suspensions or Removals,8 STUDENTS With 2 or More Suspensions or Removals,9 STUDENTS With 2 or More Suspensions or Removals,10 STUDENTS With 2 or More Suspensions or Removals_x,11 STUDENTS With 2 or More Suspensions or Removals_x,12 STUDENTS With 2 or More Suspensions or Removals_x,13 STUDENTS With 2 or More Suspensions or Removals,14 STUDENTS With 2 or More Suspensions or Removals,15 STUDENTS With 2 or More Suspensions or Removals,16 STUDENTS With 2 or More Suspensions or Removals,17 STUDENTS With 2 or More Suspensions or Removals,18 STUDENTS With 2 or More Suspensions or Removals,19 STUDENTS With 2 or More Suspensions or Removals,20 STUDENTS With 2 or More Suspensions or Removals,21 STUDENTS With 2 or More Suspensions or Removals,TOTAL STUDENTS With 2 or More Suspensions or Removals_x.2,0K STUDENTS With 2 or More Suspensions or Removals,01 STUDENTS With 2 or More Suspensions or Removals,02 STUDENTS With 2 or More Suspensions or Removals,03 STUDENTS With 2 or More Suspensions or Removals,04 STUDENTS With 2 or More Suspensions or Removals,05 STUDENTS With 2 or More Suspensions or Removals,06 STUDENTS With 2 or More Suspensions or Removals,07 STUDENTS With 2 or More Suspensions or Removals,08 STUDENTS With 2 or More Suspensions or Removals,09 STUDENTS With 2 or More Suspensions or Removals,10 STUDENTS With 2 or More Suspensions or Removals_y,11 STUDENTS With 2 or More Suspensions or Removals_y,12 STUDENTS With 2 or More Suspensions or Removals_y,TOTAL STUDENTS With 2 or More Suspensions or Removals_y.2,FEMALE STUDENTS With 2 or More Suspensions or Removals,MALE STUDENTS With 2 or More Suspensions or Removals,TOTAL STUDENTS With 2 or More Suspensions or Removals
0,01M015,P.S. 015 Roberto Clemente,Elementary,1.0,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*
1,01M019,P.S. 019 Asher Levy,Elementary,1.0,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*
2,01M020,P.S. 020 Anna Silver,Elementary,1.0,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*
3,01M034,P.S. 034 Franklin D. Roosevelt,K-8,1.0,*,*,*,*,*,*,*,14,*,*,*,*,*,*,*,14,8,6,14,8,6,14,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,14,*,*,*,*,*,*,*,*,*,*,*,*,*,14,8,6,14
4,01M063,The STAR Academy - P.S.63,Elementary,1.0,*,*,*,*,*,*,*,6,*,*,*,*,*,*,*,6,*,*,6,*,*,6,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,*,6,*,*,*,*,*,*,*,*,*,*,*,*,*,6,*,*,6

In [44]:
suspensionData.shape

(1743, 61)

In [45]:
suspensionData.describe()

       ADMINISTRATIVE DISTRICT_x
count                1742.000000
mean                   18.698622
std                    15.639696
min                     1.000000
25%                     9.000000
50%                    16.000000
75%                    26.000000
max                    97.000000

In [46]:
suspensionData.dtypes

DBN                                                                                  object
LOCATION NAME_x                                                                      object
LOCATION CATEGORY_x                                                                  object
ADMINISTRATIVE DISTRICT_x                                                           float64
AMERICAN INDIAN/ALASKAN NATIVE STUDENTS With 2 or More Suspensions or Removals_x     object
ASIAN STUDENTS With 2 or More Suspensions or Removals_x                              object
BLACK STUDENTS With 2 or More Suspensions or Removals_x                              object
HISPANIC STUDENTS With 2 or More Suspensions or Removals_x                           object
WHITE STUDENTS With 2 or More Suspensions or Removals_x                              object
MULTI-RACIAL STUDENTS With 2 or More Suspensions or Removals_x                       object
UNKNOWN STUDENTS With 2 or More Suspensions or Removals_x                            object
TOTAL STUDENTS With 2 or More Suspensions or Removals_x                              object
AMERICAN INDIAN/ALASKAN NATIVE STUDENTS With 2 or More Suspensions or Removals_y     object
ASIAN STUDENTS With 2 or More Suspensions or Removals_y                              object
BLACK STUDENTS With 2 or More Suspensions or Removals_y                              object
HISPANIC STUDENTS With 2 or More Suspensions or Removals_y                           object
WHITE STUDENTS With 2 or More Suspensions or Removals_y                              object
MULTI-RACIAL STUDENTS With 2 or More Suspensions or Removals_y                       object
UNKNOWN STUDENTS With 2 or More Suspensions or Removals_y                            object
TOTAL STUDENTS With 2 or More Suspensions or Removals_y                              object
GEN ED STUDENTS With 2 or More Suspensions or Removals_x                             object
SWD STUDENTS With 2 or More Suspensions or Removals_x                                object
TOTAL STUDENTS With 2 or More Suspensions or Removals_x.1                            object
GEN ED STUDENTS With 2 or More Suspensions or Removals_y                             object
SWD STUDENTS With 2 or More Suspensions or Removals_y                                object
TOTAL STUDENTS With 2 or More Suspensions or Removals_y.1                            object
5 STUDENTS With 2 or More Suspensions or Removals                                    object
6 STUDENTS With 2 or More Suspensions or Removals                                    object
7 STUDENTS With 2 or More Suspensions or Removals                                    object
8 STUDENTS With 2 or More Suspensions or Removals                                    object
                                                                                     ...
10 STUDENTS With 2 or More Suspensions or Removals_x                                 object
11 STUDENTS With 2 or More Suspensions or Removals_x                                 object
12 STUDENTS With 2 or More Suspensions or Removals_x                                 object
13 STUDENTS With 2 or More Suspensions or Removals                                   object
14 STUDENTS With 2 or More Suspensions or Removals                                   object
15 STUDENTS With 2 or More Suspensions or Removals                                   object
16 STUDENTS With 2 or More Suspensions or Removals                                   object
17 STUDENTS With 2 or More Suspensions or Removals                                   object
18 STUDENTS With 2 or More Suspensions or Removals                                   object
19 STUDENTS With 2 or More Suspensions or Removals                                   object
20 STUDENTS With 2 or More Suspensions or Removals                                   object
21 STUDENTS With 2 or More Suspensions or Removals                                   object
TOTAL STUDENTS With 2 or More Suspensions or Removals_x.2                            object
0K STUDENTS With 2 or More Suspensions or Removals                                   object
01 STUDENTS With 2 or More Suspensions or Removals                                   object
02 STUDENTS With 2 or More Suspensions or Removals                                   object
03 STUDENTS With 2 or More Suspensions or Removals                                   object
04 STUDENTS With 2 or More Suspensions or Removals                                   object
05 STUDENTS With 2 or More Suspensions or Removals                                   object
06 STUDENTS With 2 or More Suspensions or Removals                                   object
07 STUDENTS With 2 or More Suspensions or Removals                                   object
08 STUDENTS With 2 or More Suspensions or Removals                                   object
09 STUDENTS With 2 or More Suspensions or Removals                                   object
10 STUDENTS With 2 or More Suspensions or Removals_y                                 object
11 STUDENTS With 2 or More Suspensions or Removals_y                                 object
12 STUDENTS With 2 or More Suspensions or Removals_y                                 object
TOTAL STUDENTS With 2 or More Suspensions or Removals_y.2                            object
FEMALE STUDENTS With 2 or More Suspensions or Removals                               object
MALE STUDENTS With 2 or More Suspensions or Removals                                 object
TOTAL STUDENTS With 2 or More Suspensions or Removals                                object
Length: 61, dtype: object